### ISSUE TITLE
Failed to find Build Tools revision 26.0.2

### ISSUE THREAD

**Issue by singlepig** [googlesamples/android-PictureInPicture#7]
I cloned this repo and open it with AS 3.0.1. It failed when gradle sync, error message is:
```
Error:Failed to find Build Tools revision 26.0.2

Consult IDE log for more details (Help | Show Log)
Install Build Tools 26.0.2 and sync project
```
I've already have Build Tools 26.0.3, but not install Build Tools 26.0.2.
I know I can click the link to install Build Tools 26.0.2 to solve this problem. But what confuses me is that, I searched the whole repo, and could not find any place particularly write "26.0.2", except the README.md.
Why it need Build Tools 26.0.2 not Build Tools 26.0.3 or else?

**Comment by kengraWin** [comment]
me

**Comment by singlepig** [comment]
@kengraWin what do you mean?

**Comment by brianfox201** [comment]
This error occurs because you're using Android Gradle Plugin 3.0.0.
It requires minimum buildToolsVersion 26.0.2.

To avoid this error, remove 

buildToolsVersion 26.0.0 (Or any version you're using) from build.gradle.
Each version of the Android Gradle Plugin now has a default version of the build tools.

**Comment by singlepig** [comment]
@brianfox201 Thank you for answer!
